
!If you take a positive integer, halve it if it is even or triple it and add one if it is odd, 
!and repeat, then the number will eventually become one.
!Set up a loop containing a statement to read in a number (input terminated by zero) and to
!print out the sequence obtained from each input. The number 13 is considered to be very unlucky
!and if it is obtained as part of the sequence then execution should immediately terminate with an 
!appropriate message.
!Demonstrate that your program works by outputting the sequences generated by the following sets 
!of numbers:

!7. 106, 46, 3, 0

program mathematical_magic
implicit none

integer :: n

print *, "Vstavi število."
read *, n

if (n<=0) then
    print *, "Število mora biti naravno!"
else
    do while (n /= 1)
        if (n==13) then
            print *, "Nesrečna številka 13."
            exit
        else if (mod(n,2) == 0) then
            n = n/2
            print *, n 
        else 
            n = 3*n + 1
            print *, n
        end if
    end do
end if


end program mathematical_magic 